### PR TITLE
chore: update issue templates

### PR DESCRIPTION
**Pull request by dawnbcgov**
# Description

In preparation for moving the backlog to github projects I have:

- set up a project board: https://github.com/orgs/bcgov/projects/171 (using the BC parks board as a template)
- reviewed and updated the issue templates to reflect the way we've grouped items in the backlog, I tried to bring them inline to the templates BC Parks is using as well

## Type of change

Please delete options that are not relevant.

- [x] Chore
- [x] Documentation only

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-omrr-transparency-73-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-73-frontend.apps.silver.devops.gov.bc.ca/api/)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-omrr-transparency/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-omrr-transparency/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by dawnbcgov** [comment]
@AmanBhathal here are some changes I am proposing to the issue templates. I welcome your feedback

**Comment by mishraomp** [comment]
LGTM to me @dawnbcgov

**Comment by AmanBhathal** [comment]
@dawnbcgov Looks Good

**Comment by dawnbcgov** [comment]
Great! I'll mark as ready for review and please merge when you get the chance!

**Review by mishraomp — APPROVED** [review]
CITY

**Pull request merged**
