### PR TITLE
chore: add more details to readme

### PR DESCRIPTION
**Pull request by dawnbcgov**
# Description

Just updates the readme.

## Type of change

- [x] Documentation

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Further comments

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-omrr-transparency-144-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-144-frontend.apps.silver.devops.gov.bc.ca/api/)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-omrr-transparency/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-omrr-transparency/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by dawnbcgov** [comment]
@AmanBhathal or @mishraomp can I get a review?  Relatively minor edits! I copied the format from readmes in other bcgov repos.

**Comment by mishraomp** [comment]
thanks @dawnbcgov , LGTM

**Review by mishraomp — APPROVED** [review]

**Review by DerekRoberts — APPROVED** [review]
Documentation is aways welcome.  :)

**Comment by DerekRoberts** [comment]
@dawnbcgov @AmanBhathal Force merged since GitHub is having problems today.  Please don't learn from this example!  ;)

**Pull request merged**
